/**
/ASCII stands for American Standard Code for Information Interchange
/ASCII solved the problem that early printers had where they lacked graphic ability, so they could print out images with ASCII character.
*/
println(" |(*)   __   (*)| ");
println(" |  (       )  | ");
println("      |   |     ");
println("   |         |");
println("   (         ) ");
println("   (         ) ");
println("  (           ) ");
println("   (         ) ");
println("   (         )    ");
println("  (           ) ");
println("   (         )");
println("   (         ) ");
println("  (           ) ");
println("   (         )");
println("   (         ) ");
println("  (           )");
println("   (         )");
println("   (         ) ");
println("  (           ) ");
println("   (         ) ");
println("   (         )    ");
println("  (           ) ");
println("   (         )");
println("   (         ) ");
println("  (           ) ");
println("   (         )");
println("   (         ) ");
println("  (           ) ");
println("   (         )");
println("   (         ) ");
println("  (           ) ");
println("    (       ) "); 
println("    (       )");
println("    (       )");
println("     (     ) ");
println("     (     )");
println("     (     )");
println("      (   ) ");
println("      (   ) ");
println("      (   )");
println("       ( )");
println("       ( )");
println(" ");
println("        **      ");
println("        **      ");
println("        **      ");
println("        **      ");
println("        **       ");
println("        **        ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
println(" ");
